"""Initial migration

Revision ID: 70660163f89e
Revises: ee830477c467
Create Date: 2024-09-28 17:17:41.482715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70660163f89e'
down_revision: Union[str, None] = 'ee830477c467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donors_id'), 'donors', ['id'], unique=False)
    op.create_table('fundraisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('goal_amount', sa.Float(), nullable=True),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundraisers_id'), 'fundraisers', ['id'], unique=False)
    op.create_table('nfc_readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('assigned_fundraiser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_fundraiser_id'], ['fundraisers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfc_readers_id'), 'nfc_readers', ['id'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('nfc_reader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['nfc_reader_id'], ['nfc_readers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_nfc_readers_id'), table_name='nfc_readers')
    op.drop_table('nfc_readers')
    op.drop_index(op.f('ix_fundraisers_id'), table_name='fundraisers')
    op.drop_table('fundraisers')
    op.drop_index(op.f('ix_donors_id'), table_name='donors')
    op.drop_table('donors')
    # ### end Alembic commands ###
